#!/bin/bash

#  https://laravel.com/docs/5.4/homestead#updating-homestead
vagrant box update
git fetch upstream
git pull upstream master
git push origin master

composer update

# update after composer
git commit -a
